[WIP] Upgrade EVS to 1.1
xen-troops/android_vendor_xen_evs pull request #5
Opened 2020-09-29 12:13 UTC by rshym

2020-09-29 12:14 UTC, rshym commented
Includes commit from #4

2020-10-01 14:49 UTC, arminn requested changes

2020-10-01 14:49 UTC, arminn commented on apps/default/Android.bp
> +        //"LabeledChecker.png",
Do we need those comments here?

2020-10-01 14:49 UTC, arminn commented on apps/default/Android.bp
> +//}
Do we need those comments here?

2020-10-01 14:49 UTC, arminn commented on apps/default/Android.bp
> +//}
Do we need those comments here?

2020-10-01 14:49 UTC, arminn commented on sampleDriver/Android.bp
> +//}
Do we need those comments here?

2020-10-02 08:54 UTC, rshym commented on apps/default/Android.bp
> +        //"LabeledChecker.png",
Commented lines are removed.

2020-10-02 08:54 UTC, rshym commented on apps/default/Android.bp
> +//}
Commented lines are removed.

2020-10-02 08:54 UTC, rshym commented on apps/default/Android.bp
> +//}
Commented lines are removed.

2020-10-02 08:54 UTC, rshym commented on sampleDriver/Android.bp
> +//}
Commented lines are removed.

2020-10-02 09:32 UTC, merged